// <auto-generated />
using CarSheets_ServiceAuto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarSheets_ServiceAuto.Migrations
{
    [DbContext(typeof(CarSheets_ServiceAutoContext))]
    [Migration("20201228150927_CarSheet")]
    partial class CarSheet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarSheets_ServiceAuto.Models.CarSheet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descriereDefectiuni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("luniGarantie")
                        .HasColumnType("int");

                    b.Property<string>("nrIdentificareTalon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrInmatriculare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalPlata")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("CarSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
